//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KPIEntities : DbContext
    {
        public KPIEntities()
            : base("name=KPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kpi_Ability> kpi_Ability { get; set; }
        public virtual DbSet<kpi_AbilityGrade> kpi_AbilityGrade { get; set; }
        public virtual DbSet<kpi_AbilityRate> kpi_AbilityRate { get; set; }
        public virtual DbSet<kpi_AbilitySet> kpi_AbilitySet { get; set; }
        public virtual DbSet<kpi_AbilityType> kpi_AbilityType { get; set; }
        public virtual DbSet<kpi_Perfomance> kpi_Perfomance { get; set; }
        public virtual DbSet<kpi_PerfomanceKey> kpi_PerfomanceKey { get; set; }
        public virtual DbSet<kpi_PerfomanceLevel> kpi_PerfomanceLevel { get; set; }
        public virtual DbSet<kpi_PerfomanceRate> kpi_PerfomanceRate { get; set; }
        public virtual DbSet<kpi_PerfomanceType> kpi_PerfomanceType { get; set; }
        public virtual DbSet<kpi_SetGoal> kpi_SetGoal { get; set; }
        public virtual DbSet<kpi_StatusAbility> kpi_StatusAbility { get; set; }
        public virtual DbSet<kpi_Total> kpi_Total { get; set; }
        public virtual DbSet<kpi_Year> kpi_Year { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<umsgroup> umsgroups { get; set; }
        public virtual DbSet<umsuser> umsusers { get; set; }
    }
}
