//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_AbilityRate
    {
        public int KAR_ID { get; set; }
        public Nullable<int> KAR_AbilScore { get; set; }
        public Nullable<int> KAR_Score { get; set; }
        public Nullable<int> KAR_Status { get; set; }
        public Nullable<System.DateTime> KAR_Date { get; set; }
        public string KAR_UploadFlie { get; set; }
        public Nullable<int> KAS__ID { get; set; }
        public Nullable<int> ums_ID { get; set; }
        public Nullable<int> KPY_ID { get; set; }
    
        public virtual kpi_AbilitySet kpi_AbilitySet { get; set; }
        public virtual kpi_Year kpi_Year { get; set; }
        public virtual umsuser umsuser { get; set; }
    }
}
