//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_AbilitySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kpi_AbilitySet()
        {
            this.kpi_AbilityRate = new HashSet<kpi_AbilityRate>();
        }
    
        public int KAS_ID { get; set; }
        public Nullable<double> KAS_LenghtScore { get; set; }
        public Nullable<int> KPY_ID { get; set; }
        public Nullable<int> KAB_ID { get; set; }
        public Nullable<int> KSA_ID { get; set; }
    
        public virtual kpi_Ability kpi_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_AbilityRate> kpi_AbilityRate { get; set; }
        public virtual kpi_StatusAbility kpi_StatusAbility { get; set; }
        public virtual kpi_Year kpi_Year { get; set; }
    }
}
