//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_Year
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kpi_Year()
        {
            this.kpi_AbilityGrade = new HashSet<kpi_AbilityGrade>();
            this.kpi_AbilityRate = new HashSet<kpi_AbilityRate>();
            this.kpi_AbilitySet = new HashSet<kpi_AbilitySet>();
            this.kpi_Perfomance = new HashSet<kpi_Perfomance>();
            this.kpi_PerfomanceType = new HashSet<kpi_PerfomanceType>();
            this.kpi_SetGoal = new HashSet<kpi_SetGoal>();
            this.kpi_Total = new HashSet<kpi_Total>();
        }
    
        public int KPY_ID { get; set; }
        public string KPY_Name { get; set; }
        public Nullable<System.DateTime> KPY_StartDate { get; set; }
        public Nullable<System.DateTime> KPY_EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_AbilityGrade> kpi_AbilityGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_AbilityRate> kpi_AbilityRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_AbilitySet> kpi_AbilitySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_Perfomance> kpi_Perfomance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_PerfomanceType> kpi_PerfomanceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_SetGoal> kpi_SetGoal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_Total> kpi_Total { get; set; }
    }
}
