//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_PerfomanceLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kpi_PerfomanceLevel()
        {
            this.kpi_SetGoal = new HashSet<kpi_SetGoal>();
        }
    
        public int KPL_ID { get; set; }
        public Nullable<int> KPL_Number { get; set; }
        public string KPL_Desc { get; set; }
        public Nullable<int> KPL_MaxWeight { get; set; }
        public Nullable<int> KPL_MinWeight { get; set; }
        public Nullable<int> KPK_ID { get; set; }
    
        public virtual kpi_PerfomanceKey kpi_PerfomanceKey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_SetGoal> kpi_SetGoal { get; set; }
    }
}
