//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_PerfomanceRate
    {
        public int KPR_ID { get; set; }
        public Nullable<int> KPR_ScoreTech { get; set; }
        public Nullable<int> KPR_ScoreDean { get; set; }
        public string KPR_File { get; set; }
        public string KPR_Comment { get; set; }
        public Nullable<int> KPR_PerScore { get; set; }
        public Nullable<int> KPR_StatusTech { get; set; }
        public Nullable<int> KPR_StatusDean { get; set; }
        public Nullable<int> KSG_ID { get; set; }
        public Nullable<int> ums_ID { get; set; }
    
        public virtual kpi_SetGoal kpi_SetGoal { get; set; }
        public virtual umsuser umsuser { get; set; }
    }
}
