//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_AbilityGrade
    {
        public int KAG_ID { get; set; }
        public Nullable<int> KAG_TotalScore { get; set; }
        public double KAG_SumScore { get; set; }
        public Nullable<int> KAG_Status { get; set; }
        public string KAG_Comment1 { get; set; }
        public string KAG_Comment2 { get; set; }
        public Nullable<int> ums_ID { get; set; }
        public Nullable<int> KPY_ID { get; set; }
    
        public virtual kpi_Year kpi_Year { get; set; }
        public virtual umsuser umsuser { get; set; }
    }
}
