//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_PerfomanceKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kpi_PerfomanceKey()
        {
            this.kpi_PerfomanceLevel = new HashSet<kpi_PerfomanceLevel>();
            this.kpi_SetGoal = new HashSet<kpi_SetGoal>();
        }
    
        public int KPK_ID { get; set; }
        public Nullable<int> KPK_Number { get; set; }
        public string KPK_Name { get; set; }
        public string KPK_Comment { get; set; }
        public Nullable<int> KPM_ID { get; set; }
    
        public virtual kpi_Perfomance kpi_Perfomance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_PerfomanceLevel> kpi_PerfomanceLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kpi_SetGoal> kpi_SetGoal { get; set; }
    }
}
